export const reachImages = [
  { icon: "/districts/chickamangaluru.svg", district: "Chickamangaluru" },
  { icon: "/districts/bagalkote.svg", district: "Bagalkote" },
  { icon: "/districts/banglore.svg", district: "Bengaluru" },
  { icon: "/districts/goa.svg", district: "Goa" },
  { icon: "/districts/udupi.svg", district: "Udupi" },
  { icon: "/districts/hassan.svg", district: "Hassan" },
  { icon: "/districts/shimoga.svg", district: "Shimoga" },
  { icon: "/districts/ballari.svg", district: "Ballari" },
  { icon: "/districts/belagavi.svg", district: "Belagavi" },
  { icon: "/districts/chitradurga.svg", district: "Chitradurga" },
  { icon: "/districts/davangere.svg", district: "Davangere" },
  { icon: "/districts/dharwad.svg", district: "Dharwad" },
  { icon: "/districts/gadag.svg", district: "Gadag" },
  { icon: "/districts/haveri.svg", district: "Haveri" },
  { icon: "/districts/kodagu.svg", district: "Kodagu" },
  { icon: "/districts/koppal.svg", district: "Koppal" },
  { icon: "/districts/uttara-kannada.svg", district: "Uttara kannada" },
  { icon: "/districts/vijayanagara.svg", district: "Vijayanagara" },
];
